### ISSUE TITLE
⚡ Feature | Ability to insert some code formatted in the story

### ISSUE THREAD

**Issue by christophechevalier** [sigle/sigle#26]
It would be nice to have a new feature in the Editor allowing to **insert some formatted code** in the story.

Example :
`// Someting`

**Comment by pradel** [comment]
Hey thanks for the idea, this is a feature we definitely want to have :)

**Comment by selfagency** [comment]
I second this request but, tbqh, you should really just support Markdown

**Comment by pradel** [comment]
> I second this request but, tbqh, you should really just support Markdown

I love markdown, but unfortunately not everybody is familiar with it, that's why we also have to support an editor that most user know how to use :)

**Comment by selfagency** [comment]
![giphy](https://user-images.githubusercontent.com/2541728/61186859-38a18680-a638-11e9-92e7-7ec023f6ee76.gif)

https://ui.toast.com/tui-editor/

**Comment by pradel** [comment]
@selfagency sorry for the late answer, we took a look at tui-editor and we decided that it's not the experience we would like to give to our users. We rebuilt our editor some weeks ago more in a Medium / Ghost way which we think more users will be familiar with.

Our plan to allow you to insert some code will be to have custom code blocks will be to let you select the language and render the block using prism.js or other in order to have a nice highlighting of the code part :)

**Comment by pradel** [comment]
Update on this, we are in the process of migrating the editor from Slate to TipTap and code support will be added shortly after. https://github.com/pradel/sigle/issues/252

**Comment by pradel** [comment]
Added in the new editor 🚀
